service:
  name: helesta-monitor

# Settings for Serverless Dashboard
app: helesta-monitor
org: pandy

provider:
  name: aws
  runtime: nodejs12.x

resources:
  Resources:
    MilestoneTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${param:DYNAMO_MILESTONE_TABLE_NAME}
        KeySchema:
          - AttributeName: url
            KeyType: HASH
          - AttributeName: count
            KeyType: RANGE
        AttributeDefinitions:
          - AttributeName: url
            AttributeType: S
          - AttributeName: count
            AttributeType: N
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
